---
title: "STAT 184 Final Project "
author: "Jiarui Fan" 
date: "12/12"
output: html_notebook
---
```{r, warning=FALSE, message=FALSE}
# clean up R environment
rm (list = ls())
# load some packages
library(readr)
library(rvest)
library(xml2)
library(tidyverse)
library(DataComputing)
library(ggplot2)
library(tidyr)
library(lubridate)
```

## 1: Which is the Most Popular Ramen Product?

### Data Access
#### Primary data

```{r}
RamenFile<- file.choose()
```
```{r}
RamenData<- 
  data.table::fread(RamenFile) %>%
  as.data.frame()
```
```{r}
str(RamenData)
```
```{r}
head(RamenData)
```
```{r}
RamenData%>%
  group_by(n_distinct(Brand))%>%
  summarise()

```
#### Supporting data
```{r}
web_page <- "https://en.wikipedia.org/wiki/List_of_instant_noodle_brands"
SetOfTables <- web_page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
```
```{r}
length(SetOfTables)
```
```{r}
TableOfBrands <- SetOfTables[[1]]
```
```{r}
str(TableOfBrands)
```
```{r}
head(TableOfBrands)
```

### Data Wrangling
```{r}
RamenData <-
  RamenData%>%
  select(`Review #`, Brand, Variety, Style, Country, Stars)
```
```{r}
TableOfBrands<-
  TableOfBrands%>%
  select(Name, Currentowner)
```

```{r}
BigBrands<-
  RamenData%>%
  inner_join(TableOfBrands, by = c("Brand" = "Name"))
```

```{r}
BigBrands
```
```{r}
ByStars<-
  BigBrands%>%
  select(Brand, Stars, Variety)%>%
  group_by(Brand)%>%
  filter(Stars>=4.5, Stars != "Unrated")%>%
  arrange(desc(Stars))
```
```{r}
ByReview<-
  BigBrands%>%
  filter(`Review #`>=2000)%>%
  select(Variety, Country,Style,`Review #`)
```
```{r}
Reviews_Satrs<-
  ByStars%>%
  full_join(ByReview, by= "Variety")
Reviews_Satrs
```

```{r}
TwoCountry<- 
  Reviews_Satrs%>%
  filter(Country=="USA"| Country=="Japan", Stars != "NA")
TwoCountry%>%
  ggplot(aes(x=`Review #`, y = Stars, label = Variety))+geom_point(aes(color=Style))+facet_wrap(~Country)+geom_text()
```
```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```